import QtQuick 1.1

ListModel {
    id: container

    ListElement {
        record: "1"
        lastName: "Grechanik"
        firstName: "Mark"
        fullName: "Mark Grechanik"
        image: "drmark.jpg"
        email: "drmark@cs.uic.edu"
        room: "1120"
        building: "SEO"
        office: "1120 SEO"
        phone: ""
        floor: "11"
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "2"
        lastName: "Khokhar"
        firstName: "Ashfaq Ahmad"
        fullName: "Ashfaq Ahmad Khokhar"
        image: "khokar.gif"
        email: "ashfaq@uic.edu"
        room: "1013"
        building: "SEO"
        office: "1013 SEO"
        phone: "312.413.9460"
        floor: "10"
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "3"
        lastName: "Lee"
        firstName: "Der-Tsai"
        fullName: "Der-Tsai Lee"
        image: "dertsai.gif"
        email: "dtlee@iis.sinica.edu.tw"
        room: ""
        building: ""
        office: ""
        phone: ""
        floor: ""
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "4"
        lastName: "Lee"
        firstName: "Gyungho"
        fullName: "Gyungho Lee"
        image: "glee1.jpg"
        email: "ghlee@ece.uic.edu"
        room: "1032"
        building: "SEO"
        office: "1032 SEO"
        phone: "312.413.9657"
        floor: "10"
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "5"
        lastName: "Liang"
        firstName: "Jie"
        fullName: "Jie Liang"
        image: "jliang.jpg"
        email: "jliang@uic.edu"
        room: "234"
        building: "SEO"
        office: "234 SEO"
        phone: "312.355.1789"
        floor: "2"
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "6"
        lastName: "Linninger"
        firstName: "Andreas"
        fullName: "Andreas Linninger"
        image: "andlinn.jpg"
        email: "linninge@uic.edu"
        room: ""
        building: ""
        office: ""
        phone: "312.996.2581"
        floor: ""
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "7"
        lastName: "Liu"
        firstName: "Derong"
        fullName: "Derong Liu"
        image: "liu.gif"
        email: "derongliu@gmail.com"
        room: "1023"
        building: "SEO"
        office: "1023 SEO"
        phone: "312.355.4475"
        floor: "10"
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "8"
        lastName: "Mubayi"
        firstName: "Dhruv"
        fullName: "Dhruv Mubayi"
        image: "mubayi.jpg"
        email: "mubayi@math.uic.edu"
        room: "610"
        building: "SEO"
        office: "610 SEO"
        phone: "312.996.6168"
        floor: "6"
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "9"
        lastName: "Ohlsson"
        firstName: "Stellan"
        fullName: "Stellan Ohlsson"
        image: "ohlsson.jpg"
        email: "stellan@uic.edu"
        room: "1050CA"
        building: "BSB"
        office: "1050CA BSB"
        phone: "312.996.6643"
        floor: ""
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "10"
        lastName: "Ouksel"
        firstName: "Aris"
        fullName: "Aris Ouksel"
        image: "aris.html"
        email: "aris@uic.edu"
        room: "2411"
        building: "UH"
        office: "2411 UH"
        phone: "312.996.0771"
        floor: ""
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "11"
        lastName: "Banerjee"
        firstName: "Prashant"
        fullName: "Prashant Banerjee"
        image: "banerjee.gif"
        email: "banerjee@uic.edu"
        room: "3029"
        building: "ERF"
        office: "3029 ERF"
        phone: "312.996.5599"
        floor: ""
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "12"
        lastName: "Peterka"
        firstName: "Tom"
        fullName: "Tom Peterka"
        image: "tom_peterka.jpg"
        email: "tpeterka@mcs.anl.gov"
        room: ""
        building: ""
        office: ""
        phone: "630.252.4588"
        floor: ""
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "13"
        lastName: "Pless"
        firstName: "Vera"
        fullName: "Vera Pless"
        image: "pless.jpg"
        email: "vpless@uic.edu"
        room: "507"
        building: "SEO"
        office: "507 SEO"
        phone: "312.413.2177"
        floor: "5"
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "14"
        lastName: "Rao"
        firstName: "Wenjing"
        fullName: "Wenjing Rao"
        image: "wenjing1.jpg"
        email: "wenjing@ece.uic.edu"
        room: "1036"
        building: "SEO"
        office: "1036 SEO"
        phone: "312.355.0311"
        floor: "10"
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "15"
        lastName: "Rhodes"
        firstName: "Charles"
        fullName: "Charles Rhodes"
        image: "crhodes.jpg"
        email: "rhodes@uic.edu"
        room: "2136"
        building: "SES"
        office: "2136 SES"
        phone: "312.996.4868"
        floor: ""
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "16"
        lastName: "Santambrogio"
        firstName: "Marco"
        fullName: "Marco Santambrogio"
        image: "santambrogio_cs_web.jpg"
        email: "msanta4@uic.edu"
        room: ""
        building: ""
        office: ""
        phone: ""
        floor: ""
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "17"
        lastName: "Schonfeld"
        firstName: "Dan"
        fullName: "Dan Schonfeld"
        image: "schonfeld.gif"
        email: "ds@ece.uic.edu"
        room: "1104"
        building: "SEO"
        office: "1104 SEO"
        phone: "312.996.5847"
        floor: "11"
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "18"
        lastName: "Super"
        firstName: "Boaz"
        fullName: "Boaz Super"
        image: "super.gif"
        email: "super@cs.uic.edu"
        room: ""
        building: ""
        office: ""
        phone: ""
        floor: ""
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "19"
        lastName: "Turan"
        firstName: "Gyorgy"
        fullName: "Gyorgy Turan"
        image: "turan.gif"
        email: "gyt@uic.edu"
        room: "425"
        building: "SEO"
        office: "425 SEO"
        phone: "312.413.2151"
        floor: "4"
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "20"
        lastName: "Wiley"
        firstName: "Jennifer"
        fullName: "Jennifer Wiley"
        image: "wiley.jpg"
        email: "jwiley@uic.edu"
        room: "1054D"
        building: "BSB"
        office: "1054D BSB"
        phone: "312.355.2501"
        floor: ""
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "21"
        lastName: "Wilkinson"
        firstName: "Leland"
        fullName: "Leland Wilkinson"
        image: "leland.jpg"
        email: "leland.wilkinson@systat.com"
        room: ""
        building: ""
        office: ""
        phone: "312.651.3270"
        floor: ""
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "22"
        lastName: "Banerjee"
        firstName: "Prith"
        fullName: "Prith Banerjee"
        image: "prithBanerjee.jpg"
        email: ""
        room: ""
        building: ""
        office: ""
        phone: ""
        floor: ""
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "23"
        lastName: "Zefran"
        firstName: "Milos"
        fullName: "Milos Zefran"
        image: "zefran.gif"
        email: "mzefran@uic.edu"
        room: "1028"
        building: "SEO"
        office: "1028 SEO"
        phone: "312.996.6495"
        floor: "10"
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "24"
        lastName: "Bell"
        firstName: "John"
        fullName: "John Bell"
        image: "bell.gif"
        email: "jbell@uic.edu"
        room: "1035"
        building: "SEO"
        office: "1035 SEO"
        phone: "312.413.9054"
        floor: "10"
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "25"
        lastName: "Berger-Wolf"
        firstName: "Tanya"
        fullName: "Tanya Berger-Wolf"
        image: "berger-wolf.gif"
        email: "tanyabw@cs.uic.edu"
        room: "1136"
        building: "SEO"
        office: "1136 SEO"
        phone: "312.413.8719"
        floor: "11"
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "26"
        lastName: "Bernstein"
        firstName: "Daniel J."
        fullName: "Daniel J. Bernstein"
        image: "bernstein.jpg"
        email: "djb@math.uic.edu"
        room: "SEO"
        building: "410"
        office: "SEO 410"
        phone: "312.413.9322"
        floor: ""
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "27"
        lastName: "Buy"
        firstName: "Ugo"
        fullName: "Ugo Buy"
        image: "buy.gif"
        email: "buy@cs.uic.edu"
        room: "1139"
        building: "SEO"
        office: "1139 SEO"
        phone: "312.413.2296"
        floor: "11"
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "28"
        lastName: "Cruz"
        firstName: "Isabel"
        fullName: "Isabel Cruz"
        image: "cruz.gif"
        email: "ifc@cs.uic.edu"
        room: "1134"
        building: "SEO"
        office: "1134 SEO"
        phone: "708.269.5075"
        floor: "11"
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "29"
        lastName: "Bhaskar"
        firstName: "Bhaskar"
        fullName: "Bhaskar Bhaskar"
        image: "dasgupta.gif"
        email: "dasgupta@cs.uic.edu"
        room: "933"
        building: "SEO"
        office: "933 SEO"
        phone: "312.355.1319"
        floor: "9"
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "30"
        lastName: "Tom"
        firstName: "Tom"
        fullName: "Tom Tom"
        image: "defanti.gif"
        email: "tom@uic.edu"
        room: "2032"
        building: "ERF"
        office: "2032 ERF"
        phone: "312.996.3002"
        floor: ""
        subdept: "AdjunctFaculty"
    }
    ListElement {
        record: "31"
        lastName: "Eugenio"
        firstName: "Barbara Di"
        fullName: "Barbara Di Eugenio"
        image: "dieugenio.gif"
        email: "bdieugen@cs.uic.edu"
        room: "916"
        building: "SEO"
        office: "916 SEO"
        phone: "312.996.7566"
        floor: "9"
        subdept: "Faculty"
    }
    ListElement {
        record: "32"
        lastName: "Eriksson"
        firstName: "Jakob"
        fullName: "Jakob Eriksson"
        image: "eriksson.jpg"
        email: "jakob@uic.edu"
        room: "1135"
        building: "SEO"
        office: "1135 SEO"
        phone: "312.996.0481"
        floor: "11"
        subdept: "Faculty"
    }
    ListElement {
        record: "33"
        lastName: "Ben-Arie"
        firstName: "Jezekiel"
        fullName: "Jezekiel Ben-Arie"
        image: "benarie.jpg"
        email: "benarie@ece.uic.edu"
        room: "1020"
        building: "SEO"
        office: "1020 SEO"
        phone: "312.996.2648"
        floor: "10"
        subdept: "Faculty"
    }
    ListElement {
        record: "34"
        lastName: "Gmytrasiewicz"
        firstName: "Piotr"
        fullName: "Piotr Gmytrasiewicz"
        image: "gmytrasiecz.gif"
        email: "piotr@cs.uic.edu"
        room: "935"
        building: "SEO"
        office: "935 SEO"
        phone: "312.355.1320"
        floor: "9"
        subdept: "Faculty"
    }
    ListElement {
        record: "35"
        lastName: "Johnson"
        firstName: "Andrew"
        fullName: "Andrew Johnson"
        image: "johnson.gif"
        email: "ajohnson@uic.edu"
        room: "2032"
        building: "ERF"
        office: "2032 ERF"
        phone: "312.996.3002"
        floor: ""
        subdept: "Faculty"
    }
    ListElement {
        record: "36"
        lastName: "Kenyon"
        firstName: "Robert"
        fullName: "Robert Kenyon"
        image: "kenyon.gif"
        email: "kenyon@uic.edu"
        room: "1133"
        building: "SEO"
        office: "1133 SEO"
        phone: "312.996.0450"
        floor: "11"
        subdept: "Faculty"
    }
    ListElement {
        record: "37"
        lastName: "Kshemkalyani"
        firstName: "Ajay"
        fullName: "Ajay Kshemkalyani"
        image: "kshemkalyani.gif"
        email: "ajayk@cs.uic.edu"
        room: "915"
        building: "SEO"
        office: "915 SEO"
        phone: "312.355.1309"
        floor: "9"
        subdept: "Faculty"
    }
    ListElement {
        record: "38"
        lastName: "Leigh"
        firstName: "Jason"
        fullName: "Jason Leigh"
        image: "leigh.gif"
        email: "spiff@uic.edu"
        room: "2032"
        building: "ERF"
        office: "2032 ERF"
        phone: "312.996.3002"
        floor: ""
        subdept: "Faculty"
    }
    ListElement {
        record: "39"
        lastName: "Lilli"
        firstName: "John"
        fullName: "John Lilli"
        image: "lillis.gif"
        email: "jlillis@cs.uic.edu"
        room: "908"
        building: "SEO"
        office: "908 SEO"
        phone: "312.355.1317"
        floor: "9"
        subdept: "Faculty"
    }
    ListElement {
        record: "40"
        lastName: "Liu"
        firstName: "Bing"
        fullName: "Bing Liu"
        image: "bliu.gif"
        email: "liub@cs.uic.edu"
        room: "931"
        building: "SEO"
        office: "931 SEO"
        phone: "312.355.1318"
        floor: "9"
        subdept: "Faculty"
    }
    ListElement {
        record: "41"
        lastName: "Lyons"
        firstName: "Leilah"
        fullName: "Leilah Lyons"
        image: "llyons.jpg"
        email: "llyons@uic.edu"
        room: "918"
        building: "SEO"
        office: "918 SEO"
        phone: ""
        floor: "9"
        subdept: "Faculty"
    }
    ListElement {
        record: "42"
        lastName: "Moher"
        firstName: "Tom"
        fullName: "Tom Moher"
        image: "moher.gif"
        email: "moher@uic.edu"
        room: "3009"
        building: "ERF"
        office: "3009 ERF"
        phone: "312.996.4562"
        floor: ""
        subdept: "Faculty"
    }
    ListElement {
        record: "43"
        lastName: "Murata"
        firstName: "Tadao"
        fullName: "Tadao Murata"
        image: "murata.gif"
        email: "murata@cs.uic.edu"
        room: "1107"
        building: "SEO"
        office: "1107 SEO"
        phone: "312.996.2307"
        floor: "11"
        subdept: "Faculty"
    }
    ListElement {
        record: "44"
        lastName: "Cetinkunt"
        firstName: "Sabri"
        fullName: "Sabri Cetinkunt"
        image: "cetinkunt.jpg"
        email: "scetin@uic.edu"
        room: "3003"
        building: "ERF"
        office: "3003 ERF"
        phone: "312.996.9611"
        floor: ""
        subdept: "Faculty"
    }
    ListElement {
        record: "45"
        lastName: "Nelson"
        firstName: "Peter"
        fullName: "Peter Nelson"
        image: "nelson.gif"
        email: "nelson@uic.edu"
        room: "838"
        building: "SEO"
        office: "838 SEO"
        phone: "312.996.3259"
        floor: "8"
        subdept: "Faculty"
    }
    ListElement {
        record: "46"
        lastName: "Reed"
        firstName: "Dale"
        fullName: "Dale Reed"
        image: "reed.gif"
        email: "reed@cs.uic.edu"
        room: "917"
        building: "SEO"
        office: "917 SEO"
        phone: "312.413.9478"
        floor: "9"
        subdept: "Faculty"
    }
    ListElement {
        record: "47"
        lastName: "Renambot"
        firstName: "Luc"
        fullName: "Luc Renambot"
        image: "luc_renambot.jpg"
        email: "luc@evl.uic.edu"
        room: "2032"
        building: "ERF"
        office: "2032 ERF"
        phone: "312.996.3002"
        floor: ""
        subdept: "Faculty"
    }
    ListElement {
        record: "48"
        lastName: "Shatz"
        firstName: "Sol"
        fullName: "Sol Shatz"
        image: "shatz.gif"
        email: "shatz@cs.uic.edu"
        room: "817"
        building: "SEO"
        office: "817 SEO"
        phone: "3317"
        floor: "8"
        subdept: "Faculty"
    }
    ListElement {
        record: "49"
        lastName: "Sistla"
        firstName: "Prasad"
        fullName: "Prasad Sistla"
        image: "sistla.gif"
        email: "sistla@cs.uic.edu"
        room: "1033"
        building: "SEO"
        office: "1033 SEO"
        phone: "312.996.8779"
        floor: "10"
        subdept: "Faculty"
    }
    ListElement {
        record: "50"
        lastName: "Sloan"
        firstName: "Robert"
        fullName: "Robert Sloan"
        image: "sloan.gif"
        email: "sloan@uic.edu"
        room: "1112"
        building: "SEO"
        office: "1112 SEO"
        phone: "312.996.2369"
        floor: "11"
        subdept: "Faculty"
    }
    ListElement {
        record: "51"
        lastName: "Solworth"
        firstName: "Jon"
        fullName: "Jon Solworth"
        image: "solworth.gif"
        email: "solworth@cs.uic.edu"
        room: "4224B"
        building: "SEL"
        office: "4224B SEL"
        phone: "312.996.0955"
        floor: ""
        subdept: "Faculty"
    }
    ListElement {
        record: "52"
        lastName: "Theys"
        firstName: "Mitchell"
        fullName: "Mitchell Theys"
        image: "theys.gif"
        email: "mtheys@uic.edu"
        room: "941"
        building: "SEO"
        office: "941 SEO"
        phone: "312.413.9267"
        floor: "9"
        subdept: "Faculty"
    }
    ListElement {
        record: "53"
        lastName: "Troy"
        firstName: "Patrick"
        fullName: "Patrick Troy"
        image: "troy.gif"
        email: "troy@cs.uic.edu"
        room: "919"
        building: "SEO"
        office: "919 SEO"
        phone: "312.996.8521"
        floor: "9"
        subdept: "Faculty"
    }
    ListElement {
        record: "54"
        lastName: "Tsai"
        firstName: "Jeffrey"
        fullName: "Jeffrey Tsai"
        image: "tsai.gif"
        email: "tsai@cs.uic.edu"
        room: "1115"
        building: "SEO"
        office: "1115 SEO"
        phone: "312.996.9324"
        floor: "11"
        subdept: "Faculty"
    }
    ListElement {
        record: "55"
        lastName: "Dai"
        firstName: "Yang"
        fullName: "Yang Dai"
        image: "ydai.jpg"
        email: "yangdai@uic.edu"
        room: "233"
        building: "SEO"
        office: "233 SEO"
        phone: "312.413.1487"
        floor: "2"
        subdept: "Faculty"
    }
    ListElement {
        record: "56"
        lastName: "Venkatakrishnan"
        firstName: "V. N."
        fullName: "V. N. Venkatakrishnan"
        image: "venkatakrishnan.gif"
        email: "venkat@cs.uic.edu"
        room: "1131"
        building: "SEO"
        office: "1131 SEO"
        phone: "312.996.4860"
        floor: "11"
        subdept: "Faculty"
    }
    ListElement {
        record: "57"
        lastName: "Wolfson"
        firstName: "Ouri"
        fullName: "Ouri Wolfson"
        image: "wolfson.gif"
        email: "wolfson@cs.uic.edu"
        room: "1137"
        building: "SEO"
        office: "1137 SEO"
        phone: "312.996.6770"
        floor: "11"
        subdept: "Faculty"
    }
    ListElement {
        record: "58"
        lastName: "Yu"
        firstName: "Clement"
        fullName: "Clement Yu"
        image: "yu.gif"
        email: "yu@cs.uic.edu"
        room: "1100"
        building: "SEO"
        office: "1100 SEO"
        phone: "312.996.2318"
        floor: "11"
        subdept: "Faculty"
    }
    ListElement {
        record: "59"
        lastName: "Yu"
        firstName: "Philip S."
        fullName: "Philip S. Yu"
        image: "Philip_Yu.jpg"
        email: "psyu@cs.uic.edu"
        room: "1138"
        building: "SEO"
        office: "1138 SEO"
        phone: "312.996.0498"
        floor: "11"
        subdept: "Faculty"
    }
    ListElement {
        record: "60"
        lastName: "Zuck"
        firstName: "Lenore"
        fullName: "Lenore Zuck"
        image: "zuck.gif"
        email: "lenore@cs.uic.edu"
        room: "1140"
        building: "SEO"
        office: "1140 SEO"
        phone: "312.355.1339"
        floor: "11"
        subdept: "Faculty"
    }
    ListElement {
        record: "61"
        lastName: "Baker"
        firstName: "Imelda"
        fullName: "Imelda Baker"
        image: "imeldaBaker.jpg"
        email: "ifbaker@cs.uic.edu"
        room: "1116"
        building: "SEO"
        office: "1116 SEO"
        phone: "312.413.2911"
        floor: "11"
        subdept: "Faculty"
    }
    ListElement {
        record: "62"
        lastName: "Kelly"
        firstName: "Denise"
        fullName: "Denise Kelly"
        image: "deniseKelly.jpg"
        email: "denise@cs.uic.edu"
        room: "1119"
        building: "SEO"
        office: "1119 SEO"
        phone: "312.413.0130"
        floor: "11"
        subdept: "Faculty"
    }
    ListElement {
        record: "63"
        lastName: "Steward-Nelson"
        firstName: "Sherice"
        fullName: "Sherice Steward-Nelson"
        image: "Sherice_s.jpg"
        email: "steward@cs.uic.edu"
        room: "1120"
        building: "SEO"
        office: "1120 SEO"
        phone: "312.413.2282"
        floor: "11"
        subdept: "Faculty"
    }
    ListElement {
        record: "64"
        lastName: "Yuan"
        firstName: "Ivy"
        fullName: "Ivy Yuan"
        image: "iy.gif"
        email: "ivyyuan@uic.edu"
        room: "1118"
        building: "SEO"
        office: "1118 SEO"
        phone: "312.413.2285"
        floor: "11"
        subdept: "Faculty"
    }
    ListElement {
        record: "65"
        lastName: "Lathos"
        firstName: "Elena"
        fullName: "Elena Lathos"
        image: "elena_thumb.jpg"
        email: "elathos@cs.uic.edu"
        room: "905"
        building: "SEO"
        office: "905 SEO"
        phone: "312.413.4950"
        floor: "9"
        subdept: "Staff"
    }
    ListElement {
        record: "66"
        lastName: "Darabi"
        firstName: "Houshang"
        fullName: "Houshang Darabi"
        image: "darabi.jpg"
        email: "hdarabi@uic.edu"
        room: "2055"
        building: "ERF"
        office: "2055 ERF"
        phone: "312.996.6593"
        floor: ""
        subdept: "Staff"
    }
    ListElement {
        record: "67"
        lastName: "Nannapaneni"
        firstName: "Santhi"
        fullName: "Santhi Nannapaneni"
        image: "Santhi_n.jpg"
        email: "santhin@uic.edu"
        room: "905"
        building: "SEO"
        office: "905 SEO"
        phone: "312.996.2290"
        floor: "9"
        subdept: "Staff"
    }
    ListElement {
        record: "68"
        lastName: "Beltran"
        firstName: "Phil"
        fullName: "Phil Beltran"
        image: "beltran.jpg"
        email: "pbeltr1@uic.edu"
        room: "1125"
        building: "SEO"
        office: "1125 SEO"
        phone: "312.355.2419"
        floor: "11"
        subdept: "Staff"
    }
    ListElement {
        record: "69"
        lastName: "Certa"
        firstName: "Nick"
        fullName: "Nick Certa"
        image: "ncerta.jpg"
        email: "ncerta@uic.edu"
        room: "2260"
        building: "SEL"
        office: "2260 SEL"
        phone: "312.996.3182"
        floor: ""
        subdept: "Staff"
    }
    ListElement {
        record: "70"
        lastName: "Brown"
        firstName: "Maxine"
        fullName: "Maxine Brown"
        image: "Maxine-2009.jpg"
        email: "maxine@evl.uic.edu"
        room: "2032"
        building: "ERF"
        office: "2032 ERF"
        phone: "312.996.3002"
        floor: ""
        subdept: "Staff"
    }
    ListElement {
        record: "71"
        lastName: "Long"
        firstName: "Lance"
        fullName: "Lance Long"
        image: "lance_long.jpg"
        email: "llong@evl.uic.edu"
        room: "2038"
        building: "ERF"
        office: "2038 ERF"
        phone: "312.996.3002"
        floor: ""
        subdept: "Staff"
    }
    ListElement {
        record: "72"
        lastName: "Plepys"
        firstName: "Dana"
        fullName: "Dana Plepys"
        image: "dana_thumb.jpg"
        email: "dana@cs.uic.edu"
        room: "2032"
        building: "ERF"
        office: "2032 ERF"
        phone: "312.996.3002"
        floor: ""
        subdept: "Staff"
    }
    ListElement {
        record: "73"
        lastName: "Talandis"
        firstName: "Jonas"
        fullName: "Jonas Talandis"
        image: "Jonas_t.jpg"
        email: "jonast@evl.uic.edu"
        room: "2038"
        building: "ERF"
        office: "2038 ERF"
        phone: "312.996.3002"
        floor: ""
        subdept: "Staff"
    }
    ListElement {
        record: "74"
        lastName: "Verlo"
        firstName: "Alan"
        fullName: "Alan Verlo"
        image: "Alan_v.jpg"
        email: "alan@cs.uic.edu"
        room: "2038"
        building: "ERF"
        office: "2038 ERF"
        phone: "312.996.3002"
        floor: ""
        subdept: "Staff"
    }
    ListElement {
        record: "75"
        lastName: "Dillenburg"
        firstName: "John"
        fullName: "John Dillenburg"
        image: "Headshot2ds.jpg"
        email: "dillenbu@uic.edu"
        room: "800"
        building: "SEO"
        office: "800 SEO"
        phone: "312.996.5598"
        floor: "8"
        subdept: "Staff"
    }
    ListElement {
        record: "76"
        lastName: "Drake"
        firstName: "Caleb"
        fullName: "Caleb Drake"
        image: "caleb.jpg"
        email: "caleb@uic.edu"
        room: "803"
        building: "SEO"
        office: "803 SEO"
        phone: "3194"
        floor: "8"
        subdept: "Staff"
    }
    ListElement {
        record: "77"
        lastName: "Dutt"
        firstName: "Shantanu"
        fullName: "Shantanu Dutt"
        image: "dutt.jpg"
        email: "dutt@ece.uic.edu"
        room: "930"
        building: "SEO"
        office: "930 SEO"
        phone: "312.355.1314"
        floor: "9"
        subdept: "Staff"
    }
    ListElement {
        record: "78"
        lastName: "Piccininni"
        firstName: "Jack"
        fullName: "Jack Piccininni"
        image: "jackp.jpeg"
        email: "jackp@uic.edu"
        room: ""
        building: ""
        office: ""
        phone: "312.996.4246"
        floor: ""
        subdept: "Staff"
    }
    ListElement {
        record: "79"
        lastName: "Rorem"
        firstName: "Doug"
        fullName: "Doug Rorem"
        image: "rorem.gif"
        email: "rorem@cs.uic.edu"
        room: "927"
        building: "SEO"
        office: "927 SEO"
        phone: "312.996.5229"
        floor: "9"
        subdept: "Staff"
    }
    ListElement {
        record: "80"
        lastName: "Stroe"
        firstName: "Cosmin"
        fullName: "Cosmin Stroe"
        image: "CosminStroe.jpg"
        email: "cstroe1@uic.edu"
        room: "ADVIS"
        building: "Lab"
        office: "ADVIS Lab"
        phone: "312.413.3192"
        floor: ""
        subdept: "Staff"
    }
    ListElement {
        record: "81"
        lastName: "Xu"
        firstName: "Bo"
        fullName: "Bo Xu"
        image: "boxu.jpg"
        email: "boxu@cs.uic.edu"
        room: "4030"
        building: "SEL"
        office: "4030 SEL"
        phone: "312.996.4481"
        floor: ""
        subdept: "Staff"
    }
    ListElement {
        record: "82"
        lastName: "Eick"
        firstName: "Stephen"
        fullName: "Stephen Eick"
        image: "seick.jpg"
        email: "steve.eick@gmail.com"
        room: ""
        building: ""
        office: ""
        phone: "630.596.5420"
        floor: ""
        subdept: "Staff"
    }
    ListElement {
        record: "83"
        lastName: "Graupe"
        firstName: "Daniel"
        fullName: "Daniel Graupe"
        image: "graupe.gif"
        email: "graupe@ece.uic.edu"
        room: "1117"
        building: "SEO"
        office: "1117 SEO"
        phone: "312.996.3085"
        floor: "11"
        subdept: "Staff"
    }

}
